### ISSUE TITLE
fswatch not working

### ISSUE THREAD

**Issue by TenaciousDonor** [atticus-sullivan/cluttealtex#11] opened 2024-12-11 09:20 UTC
https://github.com/atticus-sullivan/cluttealtex/blob/ceac099aec22810dc0f8e8002d957445a76fbfc5/src_teal/cluttealtex.tl#L679-L703

fswatcher doesn't seem to be working. No crash, it just doesn't rebuild when the `.tex` file is touched.

**Comment by atticus-sullivan** [comment] 2024-12-11 18:07
I checked this out. Initially as far as I remember I some issues under linux as well which was the reason why I wanted to make the engine configurable (not only auto detect), see https://github.com/minoki/cluttex/pull/10. But testing it now, it is working. Maybe the issue is that the wrong event (not `Updated` but e.g. `delete + create`) is sent.

I'm closing this for now, but if the problem still persists or you have more information on this issue feel free to add more comments and I will reopen.

**Closed by atticus-sullivan** 2024-12-11 18:07 UTC
